import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Correct Poppins font
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"], // jitne chahiye utne weight select karo
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Kraviona",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // <-- Path from public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased bg-[#f9f9f9]`}
        style={{
          fontFamily: "var(--font-poppins)", // 👈 Poppins apply ho jayega
        }}
      >
        <header className="sticky top-0 left-0 z-50 ">
          <Header />
        </header>

        <main className="w-full px-6 lg:px-[10%] py-[20px]">{children}</main>

        <footer className="bg-gray-100 text-center py-6 mt-10">
          <p className="text-sm text-gray-500">
            © 2025 Kraviona. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
