import "./globals.css";
import { Header } from "@/components/Header";
import { Analytics } from "@vercel/analytics/next";
export const metadata = {
  title: "Kraviona",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // <-- Path from public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased bg-[#f9f9f9]`}>
        <header className="sticky top-0 left-0 z-50 ">
          <Header />
        </header>

        <main className="w-full px-2 lg:px-[10%] py-[10px]">{children}</main>

        <footer className="bg-gray-100 text-center py-6 mt-10">
          <p className="text-sm text-gray-500">
            © 2025 Kraviona. All rights reserved.
          </p>
        </footer>
        <Analytics />
      </body>
    </html>
  );
}
